{$stylesheets = ['https://fonts.googleapis.com/css?family=Pathway+Gothic+One|Playfair+Display:400,400i,700,700i|Work+Sans:500|Roboto:400&subset=latin-ext', 'css/animate.css', 'css/stylesheet.css']}
{include file="header.tpl" stylesheets=$stylesheets title="FizzBuzz by Kyree S. Williams"}

<div id="menu-modal">
	<div class="container">
		<div class="bars">
			<div class="bar bar-red"></div>
			<div class="bar bar-blue"></div>
			<div class="bar bar-green"></div>
		</div>
		<h2><strong>About</strong> This FizzBuzz Application</h2>
		<p>This particular FizzBuzz implementation was deliberately designed like a larger app, with modular functions and files. It utilizes Smarty templates generated by PHP to present the HTML. The styling is done in Sass, and powered by the Bootstrap framework.  JavaScript and jQuery facilitate all of the interactions, as well as communicating with the server to calculate and return the "FizzBuzz" values via JSON / AJAX communication, sort of like an API.</p>
		<p class="button-container"><a class="btn btn-primary btn-lg" href="https://github.com/kyreeswilliams/FizzBuzz">Visit the Git Repo</a></p>
	</div>
</div>
<div id="page-container">
<div id="header">
	<div class="container">
		<div id="menu-icon">
			<div class="menu-bar menu-bar-top"></div>
			<div class="menu-bar menu-bar-middle"></div>
			<div class="menu-bar menu-bar-bottom"></div>
		</div>
		<div id="logo">
			<img alt="Fizzbuzz" src="images/fizzbuzz-icon.svg">
		</div>
		<h1><strong>Fizz</strong>Buzz</h1>
	</div>
</div>
<div id="mission">
	<div class="container">
		<p id="mission-text"><strong>Mission:</strong> Print the numbers from 1 to 100. But for multiples of three, print <strong class="red">Fizz</strong> instead of the number and for multiples of five, print <strong class="blue">Buzz</strong> instead of the number. For numbers which are multiples of both three and five, print <strong class="green">FizzBuzz</strong>.</p>
		<p id="start-container">
			<button id="start" class="btn btn-primary btn-lg">Start</button>
		</p>
		<p id="controls-container">
			<button id="end" class="btn btn-primary btn-lg">End</button><button id="restart" class="btn btn-primary btn-lg">Restart</button>
		</p>
	</div>
</div>
<div id="numbers-container">
	<div class="container">
		<ul class="numbers">
		</ul>
	</div>
</div>
<div id="footer">
	<div class="container">
		<p>Design and Code Copyright &copy; {'Y'|date} Kyree S. Williams.</p>
	</div>
</div>
</div>

<script src="https://use.typekit.net/flr6kwz.js"></script>
{literal}<script>try{Typekit.load({ async: true });}catch(e){}</script>{/literal}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="js/fizzbuzz-functions.js"></script>

{include file="footer.tpl"}